###################################################################################
# The privilige user that is in sudoers
# This is a requirement, if root login is disabled (default)
###################################################################################
gruops: [
  "staff"
]
user: [
  {
    name: "myuser",
    password: "secret",
    shell: /bin/bash,
    memberOfGruops: [
        "sudo",
        "staff"
    ]
    # homeDirectory: /home/myuser,
    # sshkey:
  },
  # {
  #   name: "myuser2",
  #   password: "secret",
  #   shell: /bin/bash,
  # },
]

###################################################################################
# Local server settings
###################################################################################
localHost: [
  ServerName: "myhost",
  TimeZone: "",
#  PublicIp4Address: # script will guess it if not apply
#  PublicIp6Address: # script will guess it if not apply
]

###################################################################################
# SSHD settings
###################################################################################
ssh: [
  permitRootLogin: "no", # option yes|no
  passwordAuth: "yes", # option yes|no # please apply user with sshkey and set this to no
]

webserver: [
  nginx: "compile", # option yes|no|compile
#  nginxCompileVersion: "1.19.5",
]

stunnel: "yes" # option yes|no (RTMPS workaround for live broadcast to facebook)

letsencrypts: [
  install: true, # option true|false
  email: "",
]

bashStuff: true # option true|false